Repository WeBankPartners/we-cmdb, pull requests merged in 2020-08, with the labels that each got.

#1029 1026 upgrade table component
  cmdb-ui/src/pages/components/cmdb-table/index.js
  cmdb-ui/src/pages/designing/application-architecture-component.vue
  cmdb-ui/src/pages/designing/application-deployment-component.vue
  cmdb-ui/src/pages/designing/application-deployment.vue
  cmdb-ui/src/pages/designing/planning-component.vue
  cmdb-ui/src/pages/designing/resource-planning-component.vue
Labels: enhancement

#1038 #1033 add cmdb property encryption
  cmdb-core/pom.xml
  cmdb-core/src/main/java/com/webank/cmdb/config/ApplicationProperties.java
  cmdb-core/src/main/java/com/webank/cmdb/config/SpringAppConfig.java
  cmdb-core/src/main/java/com/webank/cmdb/service/propenc/EncryptionException.java
  cmdb-core/src/main/java/com/webank/cmdb/service/propenc/RsaBasedStringEncryptor.java
  cmdb-core/src/main/java/com/webank/cmdb/service/propenc/RsaEncryptablePropertyDetector.java
  cmdb-core/src/main/java/com/webank/cmdb/service/propenc/RsaEncryptor.java
  cmdb-core/src/main/java/com/webank/cmdb/service/propenc/RsaKeyPair.java
  cmdb-core/src/main/java/com/webank/cmdb/service/propenc/RsaKeyPairBuilder.java
  cmdb-core/src/main/java/com/webank/cmdb/service/propenc/RsaKeyPairDetector.java
  cmdb-core/src/main/resources/com/webank/cmdb/service/propenc/rsa_key
  cmdb-core/src/main/resources/com/webank/cmdb/service/propenc/rsa_key.pub
Labels: Don’t merge

#1047 1026 upgrade table component
  cmdb-ui/package.json
  cmdb-ui/src/pages/components/cmdb-table/index.js
Labels: enhancement

#1048 1013 auth assign in batch
  cmdb-ui/src/api/server.js
  cmdb-ui/src/locale/i18n/en-US.json
  cmdb-ui/src/locale/i18n/zh-CN.json
  cmdb-ui/src/pages/admin/permission-management.vue
  cmdb-ui/src/pages/admin/plugin-permission-management.vue
Labels: enhancement

#1049 #1008 Support deletion in batch add
  cmdb-ui/src/pages/components/cmdb-table/edit-modal.js
  cmdb-ui/src/pages/designing/application-architecture-component.vue
  cmdb-ui/src/pages/designing/application-deployment-component.vue
  cmdb-ui/src/pages/designing/planning-component.vue
  cmdb-ui/src/pages/designing/resource-planning-component.vue
Labels: enhancement

#1051 #1041 Filter response params
  cmdb-ui/src/pages/components/ref-select.js
Labels: enhancement

#1053 #1013 Auth assign in batch
  cmdb-ui/src/locale/i18n/en-US.json
  cmdb-ui/src/locale/i18n/zh-CN.json
  cmdb-ui/src/pages/admin/plugin-permission-management.vue
Labels: bug

#1058 #1057 Revent duplicate submission
  cmdb-ui/src/pages/designing/application-operation.vue
  cmdb-ui/src/pages/designing/ci-integrated-query-management.vue
  cmdb-ui/src/pages/designing/planning-operation.vue
Labels: enhancement

#1060 1057 revent duplicate submission
  cmdb-ui/src/pages/designing/ci-integrated-query-management.vue
Labels: enhancement
